version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - MODAL_API_URL=${MODAL_API_URL}
      - MODAL_API_TOKEN=${MODAL_API_TOKEN}
      - X_API_BEARER_TOKEN=${X_API_BEARER_TOKEN}
      - NOTIFICATION_DRIVER=${NOTIFICATION_DRIVER}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    volumes:
      - ./sources.json:/app/sources.json
    ports:
      - "3000:3000"
    restart: unless-stopped